[versions]
    modversion = "0.29.0"

# General Dependencies
    minecraft-range = "[1.21]"
    minecraft = "1.21"
    # Get versions from https://parchmentmc.org/docs/getting-started
    parchment-minecraft = "1.21"
    parchment = "2024.07.07"
    # Get versions from https://projects.neoforged.net/neoforged/neoform
    neoform = "1.21-20240613.152323" # vanilla neoforge configuration

# Kotlin
    kotlin = "2.0.0"
    kotlin-serialization = "1.7.1"

# Fabric Settings
    fabric = "0.15.11"
    fabric-api = "0.100.7+1.21"
    fabric-language-kotlin = "1.11.0+kotlin.2.0.0"

# Neoforge Settings


# Dependencies
    mixin = "0.8.5"
    mixinextras = "0.4.0"
    mixinextras-range = "[0.4.0,)"
    jsr305 = "3.0.1"
    log4j = "2.17.0"

# Test
    junit-jupiter = "5.8.1"
    junit-launcher = "1.11.2"
    gson = "2.11.0"

# Plugins
    plugin-mixin = "0.7.+"
    plugin-loom = "1.7-SNAPSHOT"
    plugin-moddev = "2.0.36-beta"

[libraries]
# Mixin
    mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
    mixinextras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }
    mixinextras-forge = { group = "io.github.llamalad7", name = "mixinextras-forge", version.ref = "mixinextras" }

# Kotlin
    kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
    kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
    kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }

# Platform
    fabric = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric" }
    fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
    fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
    minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

# Misc
    jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
    log4j = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }

# Test
    junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
    junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-launcher" }
    gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
# Kotlin
    kotlinserialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Platform
    moddevgradle = { id = "net.neoforged.moddev", version.ref = "plugin-moddev" }
    loom = { id = "fabric-loom", version.ref = "plugin-loom" }
